### ISSUE TITLE
badges.github.io

### ISSUE THREAD

**Issue by darkmorpher** [badges/badges.github.io#3]
@Mikulas 

http://badges.github.io

Links to `khancdn.eu` needs updating to http://shields.io/ version.

Alternatively, may be add a CNAME in the repository pointing to `shields.io`, since it's already been done for http://badges.github.io/shields

**Comment by Mikulas** [comment]
Thanks, I in fact even forgot this still exists. I will not be updating the old beta site though. Please migrate to a different service.
